Traceback (most recent call last):
  File "./serverPeer.py", line 212, in <module>
    p.destroy()
  File "./serverPeer.py", line 98, in destroy
    self.distributed_lock.destroy()
  File "../modules/Server/Lock/distributedLock.py", line 124, in destroy
    peerid = self.peer_list.peer(0) #get the first peer in que
  File "../modules/Server/peerList.py", line 109, in peer
    return self.peers[pid]
KeyError: 0
